services:
  currency-frontend:
    image: midr/True_Currency_Frontend:staging
    ports:
      - "5001:8080"
    depends_on:
      - currency-api
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  currency-api:
    image: midr/True_Currency_Api:staging
    ports:
      - "5002:8080"
    depends_on:
      - mariadb
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: currencies
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080

volumes:
  mariadb: